### ISSUE TITLE
ID vs Class

### ISSUE THREAD

**Issue by mikebutts** [tcjdotme/prj-rev-bwfs-dasmoto#1]
https://github.com/tcjdotme/prj-rev-bwfs-dasmoto/blob/52ab0182a3090ae4ac7696428e27ca6c22ad5083/Dasmoto/index.html#L25

While this worked, the proper way to do this is using classes, they are reusable for multiple elements and ID is a one time use thing.

**Comment by tcjdotme** [comment]
Gotcha. I suppose I used ID instead of CLASS simply because it was only applying to those three specific sections on the page. Thanks for the reminder though!
