### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [tcjdotme/prj-rev-bwfs-dasmoto#3]
Meets Expectations

Good job on this project, it looks close to spec. I one issue with using id's and you are good to go! . You did a good job keeping this readable with valid tags.

 <img src = "https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/hacksaw.jpeg"/> 
This is good and works perfectly fine. On the next project try out using a relative path ( ./resouces/img/whatever.jpg) for the sake of practice!

 Next, try to spice up the page, maybe add a background image for the header or some colors to the divs. Coolors.co has some cool schemes you can check out. Another idea is centering the image and text so it's not all left aligned.

**Comment by tcjdotme** [comment]
I should of clued into just downloading the images and loading them locally. That background image in the <h1> element was sure taking its sweet time to load, probably because hundreds of people were fetching it!

Thanks for the link, will check it out.
